### PR TITLE
Beautify OTA page, gzip compress HTML assets automatically on build

### PR DESCRIPTION
**Pull request by DeeFuse**

### CODE REVIEW

**Comment by iltis42** [comment]
One issue i see, compressing and so linking always takes places, even i did not change a single line of the code. This is a bit a blocker for me when i want to load multiple boards (e.g. 200 pce) as of this extra processing.
Is there a way to avoid this? 

xcvario@hp2:~/XCVario$ flash
Executing action: flash
Running ninja in directory /home/xcvario/XCVario/build
Executing "ninja flash"...
[1/12] Performing build step for 'bootloader'
ninja: no work to do.
[2/10] Generating /home/xcvario/XCVario/html/milligram.min.css.gz
Compressing: milligram.min.css > milligram.min.css.gz
[3/10] Generating /home/xcvario/XCVario/html/index.html.gz
Compressing: index.html > index.html.gz
[9/10] Generating binary image from built executable
esptool.py v3.3.2-dev
Creating esp32 image...
Merged 2 ELF sections
Successfully created esp32 image.
Generated /home/xcvario/XCVario/build/sensor.bin
[9/10] cd /home/xcvario/esp/esp-idf/components/esptool_py && /home/xc.../home/xcvario/esp/esp-idf/components/esptool_py/run_serial_tool.cmake
esptool.py esp32 -p /dev/ttyUSB0 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 4MB 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial.bin 0x1000 bootloader/bootloader.bin 0x10000 sensor.bin
esptool.py v3.3.2-dev
Serial port /dev/ttyUSB0
Connecting.....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, Coding Scheme None
WARNING: Detected crystal freq 41.01MHz is quite different to normalized freq 40MHz. Unsupported crystal in use?
Crystal is 40MHz
MAC: 24:0a:c4:12:1f:bc
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Flash will be erased from 0x00008000 to 0x00008fff...

**Comment by iltis42** [comment]
The download of a potential core file words, hence the "hourglass dots" are still rotating after the popup came and got acknowledged by pressing "OK". Guess we can stop this at that point, when this dialogue pops up. 
image

**Comment by DeeFuse** [comment]
It looks like your `flash` file differs from the one in the repository.
`esptool.py` wont run the CMake scripts, `idf.py` will.

Thre main reason for the rebuild every time is the build sequence for the idf scripts.
Without deleting the .gz file after building you have to run `build` twice to refresh the embedded files content.
The sequence is `Check file date / existance` > `create buildsteps` > `Build` > `Embedd files` > `Link`
The problem occures when the files are updated in the `Build` step but the PreBuild step already determined that the .gz file have not been modified, thus they are not contained in the buildsteps until you run `build` again.

I'll Update the `flash` file to make it more versatile and enable automatic flashsing of multiple chips in a row.

**Comment by iltis42** [comment]
Yes, i use the native idf.py flasher to flash the current state during development and roll this out to a couple of devices, each time the linker runs. The flash script is mainly used for ready builds, no problem there, its flashing always the build artfifact .bin.
Hence here i see the problem:
alias flash='idf.py -p /dev/ttyUSB0 flash'
normally the build trigger won't harm as there is nothing to built. IMHO we could check in the .gz file either, normally there is no change and this even could be done automized?

**Comment by DeeFuse** [comment]
In checking the .gz file lies the problem. 
If they exist in the `preBuild` step they wont be embedded if they are updated in the `buil` step.
Thats why i delete them in the `postBuild` step to force CMake to update them every time.

Why don't you use the `esptool.py` directly to flash the devices?

**Comment by iltis42** [comment]
During development there are changes in the code i want to flash, esptool would miss those changes.

**Comment by DeeFuse** [comment]
Thats true. I'd use `idf.py flash / monitor` for development. The time it takes to link the binary with the gz files is not that significant for single builds. For mass deployment I'd suggest using `esptool.py` then.
I can update the `flash` script to be a "deploy" script to mass flash chips wihtout building.

I tryed to keep the compressed assets to prevent the rebuild every time but it caused the wired behaviour mentioned above.
Feel free to give it a try to make the build system to integrate them after re/generating them.

**Comment by iltis42** [comment]
During develompent i have 3-5 different devices i want to load the latest state, each time the linker gets triggered. That's not a mass deployment but a use case i have and not linking when there is no change would be desirable by the default toolchain.

**Comment by DeeFuse** [comment]
You can comment out these lines to not delete the .gz files. But be aware that they won't be refresehed after the first re-/build then.
https://github.com/iltis42/XCVario/blob/238afabb2e29884b5e2499099c373fff266c821c/html/CMakeLists.txt#L18-L22

**Comment by iltis42** [comment]
Im my observation the issue is with index.html.gz, not with the .elf file ?!?

[2/10] Generating /home/xcvario/XCVario/html/milligram.min.css.gz
Compressing: milligram.min.css > milligram.min.css.gz
[3/10] Generating /home/xcvario/XCVario/html/index.html.gz
Compressing: index.html > index.html.gz

**Comment by DeeFuse** [comment]
Thats right, the current process is as follows: 

- PreBuild collects the files to be embedded and sees there are no .gz files. 
- Then it calls the function to generate them (producing this output)
- After that it sees that the files are newer than the cached date -> convert them to /build/index.html.gz.S
- Run the linker and create the binary
- Delete the .gz file

The problem araises when the .gz files are not deleted:

- PreBuild collects files to be embedded and finds the .gz files with the same date as the cached one (nothing to do)
- I can force convert the assets to .gz using cmake magic and dummy files, but cmake already determined that ther is nothing to do
- the linker runs and uses the /build/index.html.gz.S file which is now outdated.
-> New binary with old assets embedded

The second time I run build now (with nothing modified) following happens

- PreBuild collects files to be ebmedded and finds the .gz files with DIFFERENT date as chached (adds them to the work list)
- Converts them to the .S files
- Links everything into uptodate binary

I havent found any way to run the gzip utility before CMake collects its data and compares it cache to circumvent his problem.
The current solution is the closes one to not have to much overhead and is "user friendly"
I also tried deleting the /build/*.S files to trigger a update but that doesn't eaven cause linker errors.

The only thing that would force a rebuild of the compressed assets is a full clean which resets the CMake cache but has to recompile everything.

**Comment by iltis42** [comment]
According to @hjr, CMAKE has a unfortunately a known issue where dependencies of secondary targets, derived from other targets are not automatically built what seem's to have hit you here, so with the current build environment i see no way atm to get this round.
Building/Linking in the default toolchain on every invocation (without a single change) is no option, not only for me ;)
As Flash has still more that 300.000 Bytes free, i propose to drop the html .gz feature for now, until we really have a space issue. 20KB is not too much waste and needs less CPU for decompressing.

**Comment by DeeFuse** [comment]
For the time beeing you can disable the compression using the menuconfig section "Webserver" > "Use gzip compressed web assets" to toggle the compression without any other actions. The functionality of the code is automatically adjusted to not add the compression header to the response and server the right file.
https://github.com/iltis42/XCVario/blob/f18bf0155f7dfac2a092b1afd6cb54d1b8de0e7e/main/Kconfig.projbuild
https://github.com/iltis42/XCVario/blob/f18bf0155f7dfac2a092b1afd6cb54d1b8de0e7e/html/CMakeLists.txt#L7
https://github.com/iltis42/XCVario/blob/f18bf0155f7dfac2a092b1afd6cb54d1b8de0e7e/sdkconfig.defaults#L212-L216

**Pull request merged**
