### PR TITLE
Update cmake.yml

### PR DESCRIPTION
**Pull request by DeeFuse**
Publish build artifacts instead of pushing binary files to the repository

### CODE REVIEW

**Comment by iltis42** [comment]
I see the build artifacts do come as a .zip file, to make it easier for users to download the binary, i download the zip file, unzip and add the unzipped again to the corresponding release, means duplicated data and additional work to be done.
I haven't see the place in the yml where artifacts got zipped, so looks like its like this and can't be changed.
@DeeFuse do you have an idea if its possible to add an uncompressed artifact?
In that case i could omit this step and reference just to a download link from build artifacts and the plain file was there for installation.

**Comment by DeeFuse** [comment]
It would be possible to split the bin file and elf file into separately downloadable assets but they would be zipped nevertheless.
Build artifacts are going to be deleted after 90 days AFAK. So linking to them is not a good idea.

I could instead implement a function to create a "Release Template" with the two artifacts attached, the commit messages of the corresponding new commits as content which can e modified and released or deleted in case the build was a test.

**Comment by iltis42** [comment]
Yeah, i see linking is not an option in that case.
A release template was cool, attaching the .bin plain and the .elf zipped, also the commit messages with the list of the checkin comments quite cool idea. If it was marked as a pre-release, and once this list can be edited (a bit sorted, clarified, further commented), then the pre-release flag unchecked, this was great.

**Comment by DeeFuse** [comment]
I can do that maybe tomorrw. 
Shall I create a prerelease immedately or keep it as a template until manually accepted?
I'd suggest keeping it as a template until you cleaned up the comment.

**Comment by iltis42** [comment]
Yes, keeping it as a template for manual releasing sounds perfect.

**Pull request merged**
