### PR TITLE
Create IMU Debug screen

### PR DESCRIPTION
**Pull request by kubark42**
Create a debug screen for the IMU:

Screenshot 2023-08-08 at 8 39 15 AM

This is an attempt to add a debug screen, as per https://github.com/iltis42/XCVario/issues/241. It can be activated by `Setup`-->`System`-->`Hardware Setup`-->`Rotary Setup`-->`Screens`-->`Debug_IMU`.

Tested through all combinations of rotary setup screens, works as advertised.

I am not wedded to this particular debug screen, it was simply the easiest way I found to create something in the spirit of #241.

P.S. Also adds a new color, and some getters to the MPU class. This can be split out into other PRs in order to maximize PR atomicity.

### CODE REVIEW

**Comment by iltis42** [comment]
Debug stuff should not be listed under official screens. This is either something down below AHRS Setup. 
Why not just [g] instead of [gee] ?

**Comment by kubark42** [comment]
> Debug stuff should not be listed under official screens. This is either something down below AHRS Setup. 

I see your point. Elevating the debug to the same menu priority as the Vario, AHRS, and Gee meter could lead to confusion.

However, I quite like it as something I can click through in the air by cycling through the menus. I also foresee adding future debug screens (I wanted an NMEA one yesterday when I hooked up my XCVario to my GPS, and didn't know how to test if it was working), so with several debug screens would want the feature to be easily and intuitively discoverable. 

Splitting the debugs into each submenu would make that a little harder, although by no means is it a show-stopper.

Do you see a way to integrate both features, so it's not a tier 1 screen, but it is something discoverable and navigable?

> Why not just [g] instead of [gee] ?

I tried `g`, but I felt it could be confused for grams. This makes it pedantically clear what is meant. That's not a problem for people who are familiar with accelerometers, but if there's someone who's poking at the unit and discovering things, this could avoid some ambiguity.

**Comment by iltis42** [comment]
> Do you see a way to integrate both features, so it's not a tier 1 screen, but it is something discoverable and navigable?
Below the AHRS setup this should be far enough. Its nothing that is often needed, so one or two clicks more are acceptable.

**Comment by kubark42** [comment]
> Below the AHRS setup this should be far enough. Its nothing that is often needed, so one or two clicks more are acceptable.

In order not to make spaghetti out of the code, where would I put the menu activations for follow-up debug screens? Or are you saying that the data screen should only exist under the AHRS menu? I do think that would be a big compromise of the utility of the debug feature, since it would be somewhat random where to look and what information could be found there. `Setup-->System-->Hardware Setup-->Rotary Setup-->Screens-->Debug_XXX` is already quite deep and unlikely to get in anyone's way when doing basic setup.

Not having it on the cycled screens also means that it's hard to tie together cause and effect. If I want to see what the overall AHRS system is doing, it's nice to be able to toggle rapidly between the sensor input and the AHRS output. Less of a problem on a system without an engine, but with an engine it's good to see what tangible effect vibration has.

**Comment by iltis42** [comment]
No further work in here to move this to the right place

**Pull request closed without merging**
