### PR TITLE
FLARM warning display re-designed

### PR DESCRIPTION
**Pull request by moshe-braner**
Single larger airplane icon, color coded triangle (and number) by relative vertical position, limited duration sound that resets upon change in alarm level (or alarm aircraft ID).

### CODE REVIEW

**Comment by moshe-braner** [comment]
Only one airplane icon, the view from above with the triangle towards the traffic.  I think that this way it is easier to interpret the display at a glance (all the time I will give it when there is collision danger!).  Information about the relative altitude is given in the number (lower right) and in the color coding of the triangle (and the number): yellow (sun) above, green (ground) below, red at about the same altitude (most dangerous).

**Comment by iltis42** [comment]
> Only one airplane icon, the view from above with the triangle towards the traffic. I think that this way it is easier to interpret the display at a glance (all the time I will give it when there is collision danger!). Information about the relative altitude is given in the number (lower right) and in the color coding of the triangle (and the number): yellow (sun) above, green (ground) below, red at about the same altitude (most dangerous).
Yes, hence the problem is, the vertical display was requested like this and agreed by other users already, we can't simply drop this without a consensus in here. Speaking for myself i am not yet convinced that the new style is much better. But lets go into details:

Yes, the danger may increase with less altitude difference, hence where is exactly the limit? Are we as safe with > 20 m difference to display the triangle in (somehow safe zone indicating) green color?  Crossing another plane with 21 meters vertical separation if gliders climb differently, 20 meters may be gone in a few seconds, beside the fact that vertical accuracy of GPS, depending on sat constellation, might be already inaccurate already 20 meters, even more. Can we indicate a saver zone symbol (green triangle) at 20 meters vertical distance? 

In my opinion the color should either depend either on the alarm level, linked with the time for impact that is calculated accurately by the Flarm unit.

Then, looking outside the window to locate the other plane might get difficult e.g. at higher angles of bank. Supporting pilots in that task at best should be the goal. What is the advantage in providing a colored positive or negative number instead of a graphical representation that indicates higher or lower.

The yellow color for above, looks a bit strange IMHO, but that might be personal taste.

As the existing style we needed to support either, the code needed to support a config option in place in order to support both drawing modes. E.g. a new config item in Flarm Setup where Alarm Level e.g. "Display Style", and there two entries e.g. "Dual View"  ->  again show both views as it was with top view and tail view "Top View"   ->  new style with colors and only top view colored.

A good pictures of the new style for the handbook and a text is needed either.

**Comment by moshe-braner** [comment]
Green in this context does not mean "safe".  Yes we may choose different colors with experience.  For example, maybe use brown for "below" and blue for "above", similar to a typical AHRS display, but you said that the blue is hard to see in sunlight?  The 20m threshold for "about the same altitude" is arbitrary.  They are all dangerous situations, but need to know where to look for traffic.  I cannot think of a good way to display the relative vertical position graphically.  The true vertical angle is usually very small, if there is a FLARM alarm condition.  That's why I chose just 3 colors - and the number.  The red zone means: look near the horizon.  For the alarm level, the initial notification to the pilot is by sound not the display.  We have 3 different sounds, although they could be more different.  In SoftRF I use noticeably higher pitch for the higher alarm level.  Also I made the sound last longer for the higher alarm level, similar to what PowerFLARM Portable does.  Even after the sound notification, as a pilot I would look at the display as little as possible, since I want to find the traffic outside.  Usually with FLARM the higher alarm levels don't happen, if you take the right action after the lower-level alarm.

**Comment by moshe-braner** [comment]
"... the code needed to support a config option in place in order to support both drawing modes. ... A good pictures of the new style for the handbook and a text is needed either."
- are you requesting that I work on those things?  I could, but I don't know how to take good pictures (or screenshot, if possible).

**Comment by iltis42** [comment]
> Green in this context does not mean "safe". Yes we may choose different colors with experience. For example, maybe use brown for "below" and blue for "above", similar to a typical AHRS display, but you said that the blue is hard to see in sunlight? 
Yes, the normal blue is very hard readable on a black background, a very light blue would be much better. Light Brown and Light Blue could be an option. 

>The 20m threshold for "about the same altitude" is arbitrary. They are all dangerous situations, but need to know where to look for traffic. I cannot think of a good way to display the relative vertical position graphically. The true vertical angle is usually very small, if there is a FLARM alarm condition. That's why I chose just 3 colors - and the number. The red zone means: look near the horizon. 
Yes you are right, the true vertical angles are just small. In straight flight things are more easy. For pilots its getting hard when circling at higher angles of bank. An option could be to use the angle of pitch and bank we got from artificial horizon to improve that. 
> For the alarm level, the initial notification to the pilot is by sound not the display.  We have 3 different sounds, although they could be more different. In SoftRF I use noticeably higher pitch for the higher alarm level. Also I made the sound last longer for the higher alarm level, similar to what PowerFLARM Portable does. Even after the sound notification, as a pilot I would look at the display as little as possible, since I want to find the traffic outside. Usually with FLARM the higher alarm levels don't happen, if you take the right action after the lower-level alarm.
It happens that Flarm beeps and you can't see the other plane, so some info would be great if its like this, means the other is clearly in the blind spot (exactly behind or below), or is visible e.g. at 2 o'clock above horizon.

**Comment by iltis42** [comment]
> "... the code needed to support a config option in place in order to support both drawing modes. ... A good pictures of the new style for the handbook and a text is needed either."
> 
> * are you requesting that I work on those things?  I could, but I don't know how to take good pictures (or screenshot, if possible).

If you want to get it in fast, yes. I can help, but i am a bit busy right now with some other things, so only on a lower priority. In any case we needed a config option to support this as a new optional style with default at first as is now, then this should be easy. 
For the handbook of course i can help, hence a good text to explain advantage or drawback of both visions would be great. The pictures is not problem for me to do.

**Comment by moshe-braner** [comment]
> > "... the code needed to support a config option in place in order to support both drawing modes. ... A good pictures of the new style for the handbook and a text is needed either."
> > 
> > * are you requesting that I work on those things?  I could, but I don't know how to take good pictures (or screenshot, if possible).
> 
> If you want to get it in fast, yes. I can help, but i am a bit busy right now with some other things, so only on a lower priority. In any case we needed a config option to support this as a new optional style with default at first as is now, then this should be easy. For the handbook of course i can help, hence a good text to explain advantage or drawback of both visions would be great. The pictures is not problem for me to do.

- I can work on the config menu.  I need to learn how that works anyway, so I can add other things there that I hope to build.  I will also try and improve the FLARM warning screen further (e.g., change colors), so might as well ignore this pull request and wait for a new pull request then.

**Comment by moshe-braner** [comment]
> It happens that Flarm beeps and you can't see the other plane, so some info would be great if its like this, means the other is clearly in the blind spot (exactly behind or below), or is visible e.g. at 2 o'clock above horizon.

- yes of course, that is why we need this type of display, to help when we cannot quickly find the traffic visually.  I think the new design gives all the possible info for that purpose, direction, distance, and altitude, it just skips the second graphical icon part.

**Pull request closed without merging**
