### PR TITLE
 SetupMenuSelectCodes derived class

### PR DESCRIPTION
**Pull request by moshe-braner**
Further developed than the version in the January 2024 PR - see more comments there: https://github.com/iltis42/XCVario/pull/308

### CODE REVIEW

**Comment by iltis42** [comment]
So at the moment, if i understand correct, this PR enhances the SetupMenuSelect class by the SetupMenuSelectCodes class that enables us to specify any enum code each particular entry. 
So far i see its not yet used somewhere. If there are no negative impacts its worth to merge, Some points i still have here: 
- I saw there are (not just minor) impacts in the base class SetupMenuSelect.cpp, what tests had already been done and what tests might be good to keep an eye on?
- Why the codes are stored in vector, wouldn't be a std::map< index, code> be the better choice for a lookup without all that code iterating through the vector each time?

**Comment by moshe-braner** [comment]
"Why the codes are stored in vector, wouldn't be a std::map< index, code> be the better choice for a lookup without all that code iterating through the vector each time?"

- we are talking about short vectors (with under 10 entries), and the lookup is only done when the user presses the button, so the performance of a vector search is not an issue.  The overhead (in bytes of library code) of the fancier (more general) "map" object seems like overkill, although (1) it may already be used somewhere in XCvario? and (2) I just wasn't familiar with the "map" class, and (3) I tried to keep the base class as it as much as possible, so kept the vector of labels in it, and only added the codes in a second, separate, vector.

**Comment by moshe-braner** [comment]
Maybe a safer approach would be to write SetupMenuSelectCodes independent of SetupMenuSelect, instead of as a derived class.  Like SetupMenuSelect, it would still be derived from MenuEntry which is derived from RotaryObserver!  But then can avoid making any changes in SetupMenuSelect.

A complication is that the SetupMenuSelect constructor accepts a (SetupMenuSelect *action) function pointer.  An independent SetupMenuSelectCodes would accept a (SetupMenuSelectCodes *action).  My current implementation of SetupMenuSelectCodes accepts a (SetupMenuSelect *action) because it passes it on to the underlying SetupMenuSelect class, but the one place where I actually use an action function in this class (for the data monitor) I cast it into a (SetupMenuSelectCodes *action).  A separate class (directly derived from MenuEntry) would avoid that kludge.

**Comment by moshe-braner** [comment]
I'm re-writing it as its own class not derived from SetupMenuSelect (but of course derived from MenuEntry).  Carefully.  Found some minor issues with the previous version, so will close this PR.  In any case, this will leave SetupMenuSelect exactly as it is, so you will know it is safe.  But, also writing it so that the new class can be used exactly as the old one (passing the code is optional), so that, after testing, it can completely replace SetupMenuSelect.  The extra memory use is small, and not important, since the menu objects are deleted as you back up the tree.  Flash memory use (program size) is more important.

**Pull request closed without merging**
