### PR TITLE
Restored permanent Compass Heading Display in UL Display style if com…

### PR DESCRIPTION
**Pull request by MoskitoAndi**
…pass is enabled and calibrated.
This feature has been droped during the recent display routine optimisation.

### CODE REVIEW

**Comment by iltis42** [comment]
Hi @MoskitoAndi, why we need this code, if we can just enable compass in UL menu via setup (Compass/Wind->Display: Compass) ?

**Comment by MoskitoAndi** [comment]
Hi @iltis42, valid question. Due to the limitation in display space the standard compass/wind setup offers either wind or compass display for Retro style but not both. In UL-display style we freed up the space occupied by the S2F triangle. Thus we can offer a simultaneous display of both wind and compass. With permanent display of Speed, Altitude, QnH, Climb and Heading we have all basic parameters available with fixed display places. You can than use the setup choice to add a Wind display as well if You wish so. 
If You happen to select Compass for the Wind/Compass display, the permanent display of the heading just above the Altitude is disabled to avoid duplication. 
To me this makes sense for pilots of powered aircraft, having the (redundant) display of all relevant flight parameters available in a structured way on the Variometer device. I personally had that in for a while, used it and loved it. 
And the implementation now avoids code duplication thanks to Your recent restructure to eliminate the seperate drawULDisplay and drawULCompass routines.

**Comment by iltis42** [comment]
I see the wish to have the compass above altitude. And yes agree, without S2F arrow there is a new place where data can be displayed. There are currently more similar requests for more flexibility regarding the arrangement of data within the defined places on the screen. So this will definitively come but the proposal for that is more flexibility, some want to see S2F delta, some want to see netto vario or even battery voltage there. The idea for that for the future is a blackboard driven more granular and flexible approach, where we cut down the display method into smaller classes with a constructor to provide x/y position that can be configured by the user, instead of hardcoded approach. The timeline for that is next year spring, so we have enough time for a cool design to do that.

**Comment by MoskitoAndi** [comment]
Fair enough. If that's the plan, great! Let me know, if I can support. I'm more than happy to use my local version till then.
Amazing progress achieved in total, Esp. log. scale and short/longpress handling made a difference.

**Pull request closed without merging**
