### PR TITLE
Captive portal

### PR DESCRIPTION
**Pull request by DeeFuse**
Implement Captive Portal functionality for the OTA Server.

Tested with:

- iOS 16.4.1
- Android 11 (Samsung Galaxy XCover 4s)*
- Windows 10

*) Captive Portal "browser" is not able to open file selector for firmware upload

### CODE REVIEW

**Comment by iltis42** [comment]
Had some issue with my Xiaomi Redmi android smartphone to connect. The relevant console trace below. What happend.
I could well connect to the Wifi and also a notification popped up that "In Wlan anmelden: ESP32 OTA" what appears to be right.
Hence clicked that, the page did not open, a error message appeared insted: 

:
I (00:00:00.899) Cipher.cpp: Cipher::id() returns: 7049
I (00:00:00.904) sensor.cpp: Setup already present
I (00:00:00.908) sensor.cpp: Now setup I2C bus IO 21/22
I (00:00:00.913) I2Cbus: Port Sempaphore: 1 init
I (00:00:00.918) I2Cbus: stop timing setup 400, hold 400
I (00:00:00.922) I2Cbus: new stop timing: setup 400, hold 1900
I (00:00:00.928) I2Cbus: data timing sample 200, hold 200
I (00:00:00.933) sensor.cpp: Log level set globally to INFO 3; Max Prio: 25 Wifi: 15
I (00:00:00.940) sensor.cpp: This is ESP32 chip with 2 CPU cores, WiFi/BT/BLE, 
I (00:00:00.947) sensor.cpp: Silicon revision 1, 
I (00:00:00.951) sensor.cpp: 4MB external flash
I (00:00:00.956) sensor.cpp: QNH.get() 999.0 hPa
I (00:00:00.960) coredump: No coredump in flash
I (00:00:00.964) sensor.cpp: +++ All green, no coredump found in FLASH +++
I (00:00:00.971) Polars.cpp: Polars::begin() configured glider type:24, index:1220
I (00:00:00.978) AnalogInput.cpp: begin() unit: 1 ch:7 cal:1 att: 0
I (00:00:00.984) AnalogInput.cpp: ADC chars: unit:1 atten:0
I (00:00:00.989) AnalogInput.cpp: ESP32 ADC eFuse Vref
I (00:00:01.058) AdaptUGC.cpp: eglib_Send() &eglib:3ffc5880  hal-driv:3ffc0548 config:3ffbe6e4
I (00:00:01.059) ILI9341: init()
I (00:00:01.059) gpio: GPIO[13]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (00:00:01.068) gpio: GPIO[5]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (00:00:01.076) gpio: GPIO[15]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (00:00:01.086) ILI9341: reset IO:5 state=0
I (00:00:01.089) ILI9341: delay 10 ms
I (00:00:01.102) ILI9341: reset IO:5 state=1
I (00:00:01.102) ILI9341: delay 120 ms
I (00:00:01.222) ILI9341: delay 5 ms
I (00:00:01.227) ILI9341: delay 120 ms
I (00:00:01.347) sensor.cpp: setColor
I (00:00:01.347) sensor.cpp: drawLine
I (00:00:01.348) sensor.cpp: finish Draw
I (00:00:01.348) IpsDisplay.cpp: IpsDisplay::begin
I (00:00:01.351) AdaptUGC.cpp: eglib_Send() &eglib:3ffc5880  hal-driv:3ffc0548 config:3ffbe6e4
I (00:00:01.359) ILI9341: init()
I (00:00:01.362) gpio: GPIO[13]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (00:00:01.371) gpio: GPIO[5]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (00:00:01.380) gpio: GPIO[15]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (00:00:01.389) ILI9341: reset IO:5 state=0
I (00:00:01.393) ILI9341: delay 10 ms
I (00:00:01.406) ILI9341: reset IO:5 state=1
I (00:00:01.406) ILI9341: delay 120 ms
I (00:00:01.526) ILI9341: delay 5 ms
I (00:00:01.531) ILI9341: delay 120 ms
I (00:00:01.651) IpsDisplay.cpp: IpsDisplay::setup
I (00:00:01.651) IpsDisplay.cpp: IpsDisplay::setup
I (00:00:02.938) sensor.cpp: Rotary pressed: Do Software Update
I (00:00:02.938) sensor.cpp: Hardware Revision detected 3
I (00:00:02.939) OTA.cpp: Now start Wifi OTA
DHCP server started 
I (7105) wifi:wifi driver task: 3ffd9758, prio:23, stack:3584, core=0
I (00:00:03.305) system_api: Base MAC address is not set
I (00:00:03.305) system_api: read default base MAC address from EFUSE
I (7125) wifi:wifi firmware version: 4ad6fcc
I (7125) wifi:wifi certification version: v7.0
I (7125) wifi:config NVS flash: enabled
I (7126) wifi:config nano formating: disabled
I (7130) wifi:Init data frame dynamic rx buffer num: 32
I (7135) wifi:Init management frame dynamic rx buffer num: 32
I (7140) wifi:Init management short buffer num: 32
I (7145) wifi:Init dynamic tx buffer num: 32
I (7149) wifi:Init static rx buffer size: 1600
I (7153) wifi:Init static rx buffer num: 10
I (7156) wifi:Init dynamic rx buffer num: 32
I (00:00:03.361) wifi_init: rx ba win: 6
I (00:00:03.363) wifi_init: tcpip mbox: 32
I (00:00:03.367) wifi_init: udp mbox: 6
I (00:00:03.370) wifi_init: tcp mbox: 10
I (00:00:03.374) wifi_init: tcp tx win: 2440
I (00:00:03.378) wifi_init: tcp rx win: 2440
I (00:00:03.380) OTA.cpp: OTA::longPress() 0
I (00:00:03.386) OTA.cpp: OTA::release()
I (00:00:03.389) wifi_init: tcp mss: 540
I (00:00:03.393) wifi_init: WiFi IRAM OP enabled
I (00:00:03.397) wifi_init: WiFi RX IRAM OP enabled
I (00:00:03.959) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (7846) wifi:mode : softAP (c8:f0:9e:b5:8f:d9)
I (7849) wifi:Total power save buffer number: 16
I (7849) wifi:Init max length of beacon: 752/752
I (7850) wifi:Init max length of beacon: 752/752
SYSTEM_EVENT_AP_START
ESP WiFi started in AP mode, channel: 1 
W (00:00:04.057) Webserver.cpp: heap: 130392
I (00:00:04.061) Webserver.cpp: Starting http server on port: '80'
W (00:00:04.067) httpd: httpd_server_init: error enabling SO_REUSEADDR (109)
I (00:00:04.075) Webserver.cpp: Registering URI handlers
I (00:00:04.079) DNSServer.cpp: Starting DNS Server 0x3ffe357c
I (00:00:04.084) DNSServer.cpp: Socket created
I (00:00:04.088) DNSServer.cpp: Socket bound, port 53
I (00:00:04.093) DNSServer.cpp: Waiting for data
I (24403) wifi:new:<1,0>, old:<1,1>, ap:<1,1>, sta:<255,255>, prof:1
I (24405) wifi:station: 86:95:0d:a5:55:88 join, AID=1, bgn, 20
SYSTEM_EVENT_AP_STACONNECTED
I (00:00:20.648) WiFI-AP: station: 86:95:0d:a5:55:88 join, AID=1
I (00:00:21.029) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.4.2
SYSTEM_EVENT_ OTHER
I (00:00:21.211) DNSServer.cpp: Received type: 1 | class: 1 | Question for: connectivitycheck.gstatic.com
I (00:00:21.212) DNSServer.cpp: Received 47 bytes from 192.168.4.2 | DNS reply with len: 63
I (00:00:21.218) DNSServer.cpp: Waiting for data
I (00:00:21.294) Webserver.cpp: index.html Requested
W (25100) wifi:<ba-add>idx:4 (ifx:1, 86:95:0d:a5:55:88), tid:0, ssn:16, winSize:64
W (00:00:21.431) httpd_txrx: httpd_sock_err: error in send : 104
I (00:00:21.431) DNSServer.cpp: Received type: 1 | class: 1 | Question for: mqtt-mini.facebook.com
W (00:00:21.433) httpd_txrx: httpd_sock_err: error in recv : 104
I (00:00:21.435) DNSServer.cpp: Received 40 bytes from 192.168.4.2 | DNS reply with len: 56
I (00:00:21.449) DNSServer.cpp: Waiting for data
I (00:00:21.452) DNSServer.cpp: Received type: 1 | class: 1 | Question for: mtalk.google.com
I (00:00:21.460) DNSServer.cpp: Received 34 bytes from 192.168.4.2 | DNS reply with len: 50
I (00:00:21.469) DNSServer.cpp: Waiting for data
I (00:00:21.536) DNSServer.cpp: Received type: 1 | class: 1 | Question for: alt8-mtalk.google.com
I (00:00:21.537) DNSServer.cpp: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (00:00:21.543) DNSServer.cpp: Waiting for data
I (00:00:24.130) DNSServer.cpp: Received type: 1 | class: 1 | Question for: www.google.com
I (00:00:24.131) DNSServer.cpp: Received 32 bytes from 192.168.4.2 | DNS reply with len: 48
I (00:00:24.136) DNSServer.cpp: Waiting for data
W (00:00:24.145) httpd_uri: httpd_uri: URI '/gen_204' not found
W (00:00:27.575) httpd_parse: parse_block: request URI/header too long
W (00:00:27.576) httpd_txrx: httpd_resp_send_err: 431 Request Header Fields Too Large - Header fields are too long for server to interpret
W (00:00:27.762) httpd_uri: httpd_uri: URI '/favicon.ico' not found
I (00:00:27.778) Webserver.cpp: index.html Requested
I (00:00:30.773) DNSServer.cpp: Received type: 1 | class: 1 | Question for: play.googleapis.com
I (00:00:30.773) DNSServer.cpp: Received 37 bytes from 192.168.4.2 | DNS reply with len: 53
I (00:00:30.780) DNSServer.cpp: Waiting for data
W (00:00:30.788) httpd_uri: httpd_uri: URI '/generate_204' not found
W (00:00:33.859) httpd_uri: httpd_uri: URI '/generate_204' not found
I (00:00:36.937) DNSServer.cpp: Received type: 1 | class: 1 | Question for: alt2-mtalk.google.com
I (00:00:36.938) DNSServer.cpp: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (00:00:36.944) DNSServer.cpp: Waiting for data
I (00:00:39.238) DNSServer.cpp: Received type: 1 | class: 1 | Question for: api.facebook.com
I (00:00:39.238) DNSServer.cpp: Received 34 bytes from 192.168.4.2 | DNS reply with len: 50
I (00:00:39.244) DNSServer.cpp: Waiting for data
I (00:00:39.321) DNSServer.cpp: Received type: 1 | class: 1 | Question for: b-api.facebook.com
I (00:00:39.321) DNSServer.cpp: Received 36 bytes from 192.168.4.2 | DNS reply with len: 52
I (00:00:39.327) DNSServer.cpp: Waiting for data
I (00:00:39.331) DNSServer.cpp: Received type: 1 | class: 1 | Question for: graph.facebook.com
I (00:00:39.339) DNSServer.cpp: Received 36 bytes from 192.168.4.2 | DNS reply with len: 52
I (00:00:39.348) DNSServer.cpp: Waiting for data
I (00:00:39.354) DNSServer.cpp: Received type: 1 | class: 1 | Question for: b-graph.facebook.com
I (00:00:39.359) DNSServer.cpp: Received 38 bytes from 192.168.4.2 | DNS reply with len: 54
I (00:00:39.369) DNSServer.cpp: Waiting for data
I (00:00:44.852) DNSServer.cpp: Received type: 1 | class: 1 | Question for: portal.fb.com
I (00:00:44.852) DNSServer.cpp: Received 31 bytes from 192.168.4.2 | DNS reply with len: 47
I (00:00:44.858) DNSServer.cpp: Waiting for data
W (00:00:44.865) httpd_uri: httpd_uri: URI '/mobile/status.php' not found
W (00:00:44.882) httpd_txrx: httpd_sock_err: error in recv : 104
I (00:00:45.734) DNSServer.cpp: Received type: 1 | class: 1 | Question for: sdkconfig.ad.intl.xiaomi.com
I (00:00:45.734) DNSServer.cpp: Received 46 bytes from 192.168.4.2 | DNS reply with len: 62
I (00:00:45.741) DNSServer.cpp: Waiting for data
I (00:01:06.164) DNSServer.cpp: Received type: 1 | class: 1 | Question for: accounts.google.com
I (00:01:06.165) DNSServer.cpp: Received 37 bytes from 192.168.4.2 | DNS reply with len: 53
I (00:01:06.171) DNSServer.cpp: Waiting for data
I (00:01:06.174) DNSServer.cpp: Received type: 65 | class: 1 | Question for: accounts.google.com
I (00:01:06.182) DNSServer.cpp: Received 37 bytes from 192.168.4.2 | DNS reply with len: 53
I (00:01:06.192) DNSServer.cpp: Waiting for data
I (00:01:06.213) DNSServer.cpp: Received type: 1 | class: 1 | Question for: www.google.com
I (00:01:06.214) DNSServer.cpp: Received 32 bytes from 192.168.4.2 | DNS reply with len: 48
I (00:01:06.219) DNSServer.cpp: Waiting for data
I (00:01:06.223) DNSServer.cpp: Received type: 65 | class: 1 | Question for: www.google.com
I (00:01:06.231) DNSServer.cpp: Received 32 bytes from 192.168.4.2 | DNS reply with len: 48
I (00:01:06.239) DNSServer.cpp: Waiting for data
I (00:01:06.424) DNSServer.cpp: Received type: 1 | class: 1 | Question for: clientservices.googleapis.com
I (00:01:06.425) DNSServer.cpp: Received 47 bytes from 192.168.4.2 | DNS reply with len: 63
I (00:01:06.432) DNSServer.cpp: Waiting for data
I (00:01:06.435) DNSServer.cpp: Received type: 65 | class: 1 | Question for: clientservices.googleapis.com
I (00:01:06.444) DNSServer.cpp: Received 47 bytes from 192.168.4.2 | DNS reply with len: 63
I (00:01:06.453) DNSServer.cpp: Waiting for data
I (00:01:06.862) DNSServer.cpp: Received type: 1 | class: 1 | Question for: optimizationguide-pa.googleapis.com
I (00:01:06.862) DNSServer.cpp: Received 53 bytes from 192.168.4.2 | DNS reply with len: 69
I (00:01:06.870) DNSServer.cpp: Waiting for data
I (00:01:06.873) DNSServer.cpp: Received type: 65 | class: 1 | Question for: optimizationguide-pa.googleapis.com
I (00:01:06.883) DNSServer.cpp: Received 53 bytes from 192.168.4.2 | DNS reply with len: 69
I (00:01:06.892) DNSServer.cpp: Waiting for data
I (00:01:11.270) DNSServer.cpp: Received type: 1 | class: 1 | Question for: e8.whatsapp.net
I (00:01:11.270) DNSServer.cpp: Received 33 bytes from 192.168.4.2 | DNS reply with len: 49
I (00:01:11.276) DNSServer.cpp: Waiting for data
I (00:01:11.313) DNSServer.cpp: Received type: 1 | class: 1 | Question for: connect.intl.rom.miui.com
I (00:01:11.313) DNSServer.cpp: Received 43 bytes from 192.168.4.2 | DNS reply with len: 59
I (00:01:11.320) DNSServer.cpp: Waiting for data
W (00:01:11.332) httpd_uri: httpd_uri: URI '/generate_204' not found
W (00:01:11.570) httpd_uri: httpd_uri: URI '/chat' not found
W (00:01:11.574) httpd_parse: parse_block: incomplete (0/123) with parser error = 16
W (00:01:11.575) httpd_txrx: httpd_resp_send_err: 400 Bad Request - Server unable to understand request due to invalid syntax
I (00:01:11.614) DNSServer.cpp: Received type: 1 | class: 1 | Question for: g.whatsapp.net
I (00:01:11.614) DNSServer.cpp: Received 32 bytes from 192.168.4.2 | DNS reply with len: 48
I (00:01:11.620) DNSServer.cpp: Waiting for data
W (00:01:11.822) httpd_uri: httpd_uri: URI '/chat' not found
W (00:01:11.827) httpd_parse: parse_block: incomplete (0/123) with parser error = 16
W (00:01:11.828) httpd_txrx: httpd_resp_send_err: 400 Bad Request - Server unable to understand request due to invalid syntax
I (00:01:18.875) DNSServer.cpp: Received type: 1 | class: 1 | Question for: clients4.google.com
I (00:01:18.876) DNSServer.cpp: Received 37 bytes from 192.168.4.2 | DNS reply with len: 53
I (00:01:18.882) DNSServer.cpp: Waiting for data
I (00:01:18.885) DNSServer.cpp: Received type: 65 | class: 1 | Question for: clients4.google.com
I (00:01:18.894) DNSServer.cpp: Received 37 bytes from 192.168.4.2 | DNS reply with len: 53
I (00:01:18.903) DNSServer.cpp: Waiting for data
I (00:01:20.782) DNSServer.cpp: Received type: 1 | class: 1 | Question for: clients4.google.com
I (00:01:20.783) DNSServer.cpp: Received 37 bytes from 192.168.4.2 | DNS reply with len: 53
I (00:01:20.789) DNSServer.cpp: Waiting for data
I (00:01:20.792) DNSServer.cpp: Received type: 65 | class: 1 | Question for: clients4.google.com
I (00:01:20.801) DNSServer.cpp: Received 37 bytes from 192.168.4.2 | DNS reply with len: 53
I (00:01:20.809) DNSServer.cpp: Waiting for data
I (00:01:27.114) DNSServer.cpp: Received type: 1 | class: 1 | Question for: weatherapi.intl.xiaomi.com
I (00:01:27.114) DNSServer.cpp: Received 44 bytes from 192.168.4.2 | DNS reply with len: 60
I (00:01:27.121) DNSServer.cpp: Waiting for data
I (00:01:35.520) DNSServer.cpp: Received type: 35 | class: 1 | Question for: de-vodafone.rcs.telephony.goog
I (00:01:35.521) DNSServer.cpp: Received 48 bytes from 192.168.4.2 | DNS reply with len: 64
I (00:01:35.528) DNSServer.cpp: Waiting for data
I (00:01:37.116) DNSServer.cpp: Received type: 1 | class: 1 | Question for: alt6-mtalk.google.com
I (00:01:37.116) DNSServer.cpp: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (00:01:37.123) DNSServer.cpp: Waiting for data
I (00:01:42.525) Webserver.cpp: index.html Requested
I (00:01:42.604) Webserver.cpp: milligram.min.css Requested
I (00:01:42.695) Webserver.cpp: status.json Requested
I (00:01:42.696) coredump: No coredump available
W (00:01:57.206) httpd_uri: httpd_uri: URI '/generate_204' not found
I (00:02:05.834) DNSServer.cpp: Received type: 1 | class: 1 | Question for: update.googleapis.com
I (00:02:05.835) DNSServer.cpp: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (00:02:05.842) DNSServer.cpp: Waiting for data
I (00:02:05.845) DNSServer.cpp: Received type: 65 | class: 1 | Question for: update.googleapis.com
I (00:02:05.853) DNSServer.cpp: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (00:02:05.862) DNSServer.cpp: Waiting for data
I (00:02:05.873) DNSServer.cpp: Received type: 1 | class: 1 | Question for: update.googleapis.com
I (00:02:05.874) DNSServer.cpp: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (00:02:05.883) DNSServer.cpp: Waiting for data
I (00:02:05.886) DNSServer.cpp: Received type: 65 | class: 1 | Question for: update.googleapis.com
I (00:02:05.895) DNSServer.cpp: Received 39 bytes from 192.168.4.2 | DNS reply with len: 55
I (00:02:05.906) DNSServer.cpp: Waiting for data
W (00:02:05.911) httpd_parse: parse_block: request URI/header too long
W (00:02:05.913) httpd_txrx: httpd_resp_send_err: 431 Request Header Fields Too Large - Header fields are too long for server to interpret
I (00:02:10.946) DNSServer.cpp: Received type: 1 | class: 1 | Question for: android.apis.google.com
I (00:02:10.947) DNSServer.cpp: Received 41 bytes from 192.168.4.2 | DNS reply with len: 57
I (00:02:10.953) DNSServer.cpp: Waiting for data
I (00:02:10.957) DNSServer.cpp: Received type: 1 | class: 1 | Question for: firebaseremoteconfig.googleapis.com
I (00:02:10.966) DNSServer.cpp: Received 53 bytes from 192.168.4.2 | DNS reply with len: 69
I (00:02:10.975) DNSServer.cpp: Waiting for data
I (00:02:12.550) DNSServer.cpp: Received type: 1 | class: 1 | Question for: e10.whatsapp.net
I (00:02:12.551) DNSServer.cpp: Received 34 bytes from 192.168.4.2 | DNS reply with len: 50
I (00:02:12.556) DNSServer.cpp: Waiting for data
I (00:02:12.579) DNSServer.cpp: Received type: 1 | class: 1 | Question for: e3.whatsapp.net
I (00:02:12.580) DNSServer.cpp: Received 33 bytes from 192.168.4.2 | DNS reply with len: 49
I (00:02:12.585) DNSServer.cpp: Waiting for data
W (00:02:12.775) httpd_uri: httpd_uri: URI '/chat' not found
W (00:02:12.779) httpd_parse: parse_block: incomplete (0/123) with parser error = 16
W (00:02:12.781) httpd_txrx: httpd_resp_send_err: 400 Bad Request - Server unable to understand request due to invalid syntax
W (00:02:13.002) httpd_uri: httpd_uri: URI '/chat' not found
W (00:02:13.006) httpd_parse: parse_block: incomplete (0/123) with parser error = 16
W (00:02:13.006) httpd_txrx: httpd_resp_send_err: 400 Bad Request - Server unable to understand request due to invalid syntax
W (00:02:16.995) httpd_uri: httpd_uri: URI '/mobile/status.php' not found
W (00:02:17.218) httpd_uri: httpd_uri: URI '/generate_204' not found
I (00:02:22.780) DNSServer.cpp: Received type: 35 | class: 1 | Question for: de-vodafone.rcs.telephony.goog
I (00:02:22.781) DNSServer.cpp: Received 48 bytes from 192.168.4.2 | DNS reply with len: 64
I (00:02:22.788) DNSServer.cpp: Waiting for data

**Comment by DeeFuse** [comment]
Can you verify if `CONFIG_HTTPD_MAX_REQ_HDR_LEN=1024` is set in `sdkconfig` 
If not you might need to run `idf.py menuconfig` to update it.

I‘m curious why android has to send over 512 byte of arguments or cookie data to a captive portal endpoint.

**Comment by iltis42** [comment]
Its not set, only in .defaults, fixed that and bingo, its loading like a charm:

image

**Comment by hjr** [comment]
Have a IOS 16.4.1. phone and did some trials. 
- I can do firmware uploads.
- I have no option to save the debug dump to a file. It just resides in this temporary authentication web page as raw download and I do not see an option to save it.
- The iPhone does not allow to leave the not completed authentication page shown on the Wifi settings and switch to a web browser. The Wifi disconnects immediately when you try to leave the wifi configuration.
Can't we just somehow complete the captive portal authentication and switch to a browser which has all this functionality?

**Comment by DeeFuse** [comment]
There might be a way to open the default browser from the CaptivePortal but this might be different on any OS and version.
On iOS it might be possible as described [here](https://developer.apple.com/forums/thread/75498)
But on Android it might not be possible to do so.

Instead I would propose a change to the DNS server to resolve `http://xcvario/` and remove the CaptivePortal functionality.
In addition to that a small QR code could be displayed to a) Connect to the AP b) Open the URL

**Comment by DeeFuse** [comment]
Can you give me some more information about those smartphones or warnings when visiting an unencrypted page?
As far as I know most smartphones will show a open lock symbol but not scare you as you described it.
The only possibility I see for such messages is when a invalid certificate is beeing used - that can be a real threat.

In my opinion is using https on the xcvario not the right thing. There is no feasable way to install a trusted certificate on it.
Without a trusted certificate the uses has a "scary screen" asking them if they want to trust that - independen of Phone manufacturer. The only partially practical way would be to purchase a SSL certificate for a domain you own: e.g. `update.xcvario.de` and let the DNS server serve that URL when connected to the vario.
The problem is that you have to embedd the `private key` of that certificate on the device / firmware and it would be possible to extract from the binary with some effort. 

Regarding the QR code:
It is possible to create a `wifi qr code` which contains the SSID and Password so that your device automatically connects to it.
As soon as the vario recognizes a connection it can display a second QR Code which prompts the device to open the webbrowser with a given URL.
I got a QR gernerator libaray at hand which could be integrated for generating the bit data.

**Comment by iltis42** [comment]
Troubles i had seen with my current Xiaomi redmi smartphone that ~3 updates before did not keep the Wifi connection when it was non secure and hopped to the local Fritsbox after a minute, even it was ticked that this non secure connection had to be kept. 
The issue might have been located in the OS itself, as meanwhile this works in fact.
I have on that device now even no issue downloading a core dump, "all green" i would say with my tests on that device.
Maybe you are right and a non valid certificate creates more headache that a non secure connection, at that time i am thinking if pest or cholera is the better disease.
We should give the http://xcvario a try, and if we could keep the captive portal (at least for android) with the URL entry as a second option for iphone users at special tasks like core file download?

**Comment by DeeFuse** [comment]
I'll add the DNS entry and it might be possible to detect if the page has loaded with the captive portal browser and show a message when accessing a not working function in that specific browser.

**Comment by iltis42** [comment]
That's a great idea to keep this feature and support even iPhone users having limits with their native browsers to the best as we can.

**Comment by DeeFuse** [comment]
With the resolver as the only one there is no need for .local 
In theory you can try it right now.
The DNS responder is set up to respond to any Hostnamen with the IP. Just connect to the Wi-Fi, close the captive portal (stay connected anyways) and open any URL (even http://a/ should work)

**Review by Elvin-260 — APPROVED** [review]

**Pull request merged**
