### PR TITLE
added option of RICO style audio

### PR DESCRIPTION
**Pull request by moshe-braner**
Mainly modified ESPAudio, but also related changes in menus and settings

### CODE REVIEW

**Comment by iltis42** [comment]
I have tested the RICO style at first on a branch, and i have some comments. At the moment the RICO style is merged into the chopping option. I think this is rather something elementar, and could go into here: "Dual Tone" what is mainly gaps when off or ILEC sound (a second tone instead of a Pause). My proposal was to change the text into "Flavor" or something and and a new option: 0: "Standard Gaps", 1: "Dual Tone", 2: RICO style, or "Short Pulses". in the Chopping Style we may only feature Soft and Hard, and RICO style adjusts them both to its needs.

As i had understood this new style shall indicate a good climb by a higher number of short pulses, rather that by a rise of frequency. First i see the number of pulses is still a bit rare. Maybe its due to struggling with the fading, maybe there is another reason. There is something like just one pulse per second at 1 m/s climb. Had expected a significant higher pulse frequency. Maybe there are hardware limits, maybe we need a quicker fade-in/out method, something in between hard and soft. Guess this needs a bit more work to get a good compromise here.

Second, at the moment i see the frequency is altered in the same way as before. Is this intended, means a part of standard RICO style? I think RICO makes good sense to stress those frequencies more, that are well audible and not nerving high. ATM both takes place, what is your opinion to this?

Soft chopping is too soft IMHO, at 5 m/s i hear almost no difference to the default audio style, meanwhile hard chopping sounds like a chicken. Below i have shared a video another contributor sent me to compare the center aid's and we hear the sound of a vario that gives short pulses either. Do you think this sound is similar to RICO style? This sounds good in my opinion. 

Have done some first adjustments in my branch https://github.com/iltis42/XCVario/tree/rico_audio, here:
https://github.com/iltis42/XCVario/commit/0090e834aaefa75a513f71dc2b76b6939316d93b
you may check, e.g. the fade in/out steps reduced from 5->3 (still work to be done, e.g. only do this for RICO), higher frequency of pulses by reducing the period, and also removed the fix 10mS delay (not beneficial IMHO there). 
You may check my changes (merge to your your branch or takeover manually) and comment your opinion here. Thanks!

**Comment by iltis42** [comment]
Here a short video made with the status of rico_audio branch as posted minutes ago.
https://www.youtube.com/watch?v=V7uKGBq4Duo

**Comment by moshe-braner** [comment]
I see you changed to 5 ms task ticks.  That may help (to allow 10ms RICO clicks without delay()).  I'd therefore change the two conditional processing places to (tick&0x7) and (tick&0x3F) accordingly.  Processing always happens if "scheduled".  But 25 ms RICO clicks are too long in my view - for the "hard" version of RICO.  Can have 25 ms soft and 10 ms hard?  Those are very different styles, the "soft" more like short "beeps", the "hard" more like "clicks".

**Comment by iltis42** [comment]
This PR is in the rico_audio branch and not yet ready for master. Further adjustmens i can fetch from your rico_audio branch

**Pull request closed without merging**
