### PR TITLE
Beautify OTA website, move OTA Server out of component into main

### PR DESCRIPTION
**Pull request by DeeFuse**
Reworked OTA UI with milligram.css, no jQuery dependency and better upload progressbar.

Additional ideas: 
- supersed "MyWifi.cpp", "WifiApp.cpp" "WifiClient.cpp" into common "Wifi" class for handling STA / AP functionality.
- Debug mode starts Webserver in regular operation to expose a Taskmanager like interface for Thread stack monitoring and load analysis.

### CODE REVIEW

**Comment by iltis42** [comment]
Will look into that next week.

**Comment by DeeFuse** [comment]
You can merge my PR into the master branch after the latest commit in which fixed the "software_update" flag.
After that you have a combination of both branches changes -> new OTA UI + fixed flag

**Comment by iltis42** [comment]
> You can merge my PR into the master branch after the latest commit in which fixed the "software_update" flag. After that you have a combination of both branches changes -> new OTA UI + fixed flag

The tests look good now after the last fix, some minor thing like "Software Update" instead in only "System Info" i prefer for the first tab to keep consistent with the other tabs that name the action that can be done there. 
The history of the Webserver.cpp is lost what makes is a bit difficult to track the changes, guess you decided to rewrite the  webserver from scratch, thats why it was added i see also file and OTAServer.cpp got deleted from git. Hence in this case better do a "git mv" to the new filename to get a track of the history (even the change is big in that file).

image

**Comment by DeeFuse** [comment]
I tried moving it but it keeps showing it as "Deleted" + "New" and the history is gone.
I've created a test branch with the same changes but using "git mv" to move the files.
https://github.com/DeeFuse/XCVario/commits/ota-test/main/Webserver.cpp
grafik

**Pull request merged**
